---
- name: Ansible preconditions
  apt: "pkg=software-properties-common state=latest"

- name: Add Ansible PPA
  apt_repository: "repo='ppa:ansible/ansible' update_cache=yes"

- name: Install Ansible
  register: result
  apt: "pkg=ansible state=latest"  
 
- fail: msg="Ansible updated please restart."
  when: result.changed == true

  
